Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7.5"
  c.vm.hostname = "base-centos-75.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/eljeffe/work/winhab/base", "/tmp/habitat", nil
  c.vm.synced_folder "/Users/eljeffe/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-base-base-centos-75-07adee90-03ad-4913-8d55-d82dda4016fb"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
