scaffold_policy_name="base"
pkg_name=base
pkg_origin=aig
pkg_version="0.2.0"
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_description="The Wabtec $scaffold_policy_name Policy"
pkg_upstream_url="http://chef.io"
pkg_scaffolding="chef/scaffolding-chef-infra"
pkg_svc_user=("root")
